; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[administerusersbyrole][version] = "1.0-beta1"

projects[aranea_base][location] = ""
projects[aranea_base][version] = "1.0-alpha1"

projects[aranea_blog][location] = ""
projects[aranea_blog][version] = "2.0-alpha"

projects[aranea_gallery][location] = ""
projects[aranea_gallery][version] = "1.0-beta"

projects[bintangtimur_alumni][location] = ""
projects[bintangtimur_alumni][version] = "1.0-alpha"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[bintangtimur_settings][download][type] = ""
projects[bintangtimur_settings][download][url] = ""
projects[bintangtimur_settings][location] = ""
projects[bintangtimur_settings][type] = "module"
projects[bintangtimur_settings][version] = "1.0-alpha"

projects[ctools][version] = "1.3"

projects[ckeditor][version] = "1.13"

projects[date][version] = "2.6"

projects[entity][version] = "1.1"

projects[features][version] = "2.0-rc1"

projects[feeds][version] = "2.0-alpha8"

projects[filefield_sources][version] = "1.8"

projects[filefield_sources_plupload][version] = "1.0"

projects[imageapi][version] = "1.x-dev"

projects[imce][version] = "1.7"

projects[job_scheduler][version] = "2.0-alpha3"

projects[lightbox2][version] = "1.0-beta1"

projects[plupload][version] = "1.1"

projects[profile2][version] = "1.3"

projects[profile2_regpath][version] = "1.12"

projects[strongarm][version] = "2.0"

projects[uuid][version] = "1.0-alpha4"

projects[uuid_features][version] = "1.0-alpha3"

projects[views][version] = "3.7"

projects[views_slideshow][version] = "3.0"

projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
projects[nucleus][subdir] = "nucleus"
projects[nucleus][version] = "1.3"

projects[tb_purity][version] = "1.0-beta1"

; Modules
projects[bintangtimur_views][type] = "module"
projects[bintangtimur_views][download][type] = "git"
projects[bintangtimur_views][download][url] = "ssh://git@bitbucket.org/septianw/bintangtimur-views.git"
projects[bintangtimur_views][download][revision] = "6de44870ec1901e2baa2f52c47336fb13d034316"

